---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oathkeeper-maester
  namespace: ory
spec:
  install:
    remediation:
      retries: -1
  releaseName: oathkeeper-maester
  chart:
    spec:
      chart: oathkeeper-maester
      sourceRef:
        kind: HelmRepository
        name: ory
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: oathkeeper-maester-values
