logLevel: trace
selfAddress: 5E1qGsfiQo62EYYKo86Lf9sALgcWN8jJJvnywaY3eNrkTaut
externalDscpNode:
  host: node-3pl-a-dscp-node-0
  port: 9944
authType: EXTERNAL
ingress:
  ingressClassName: nginx-3pl-a
  hostname: 3pl-a.dsch-l3.com
  paths:
    - path: "/v1/members"
      pathType: Prefix
    - path: "/v1/self"
      pathType: Prefix
node:
  enabled: false
postgresql:
  primary:
    persistence:
      storageClass: enc-managed-csi
      size: 1Gi
image:
  tag: v1.8.29
