logLevel: trace
selfAddress: 5GUNKMhgabNPDSJnVosU1Qt5ZuR9LUS78Pnt54UTGn15q3cy
externalDscpNode:
  host: node-3pl-a-dscp-node-0
  port: 9944
externalOrigin: "https://3pl-a.dsch-l3.com"
externalPathPrefix: "identity"
authType: EXTERNAL
ingress:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  ingressClassName: nginx-3pl-a
  hostname: 3pl-a.dsch-l3.com
  paths:
    - path: "/identity/(.*)"
      pathType: Prefix
node:
  enabled: false
postgresql:
  persistence:
    storageClass: enc-managed-csi
    size: 1Gi
image:
  tag: v1.8.26
