logLevel: info
selfAddress: 5E1qGsfiQo62EYYKo86Lf9sALgcWN8jJJvnywaY3eNrkTaut
externalDscpNode:
  host: node-3pl-a-dscp-node-0
  port: 9944
externalOrigin: "https://3pl-a.dsch-l3.com"
authType: EXTERNAL
ingress:
  hostname: 3pl-a.dsch-l3.com
node:
  enabled: false
postgresql:
  persistence:
    storageClass: enc-managed-csi
    size: 1Gi
