logLevel: debug
selfAddress: 5E1qGsfiQo62EYYKo86Lf9sALgcWN8jJJvnywaY3eNrkTaut
externalDscpNode:
  host: node-3pl-a-dscp-node-0
  port: 9944
externalOrigin: "https://3pl-a.dsch-l3.com"
externalPathPrefix: "identity"
authType: EXTERNAL
apiVersion: v1
ingress:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  ingressClassName: nginx-3pl-a
  hostname: 3pl-a.dsch-l3.com
  paths:
    - path: "/identity/(.*)"
      pathType: Prefix
node:
  enabled: false
postgresql:
  persistence:
    storageClass: enc-managed-csi
    size: 1Gi
