---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: oathkeeper-sync
  namespace: ory
spec:
  interval: 1m
  path: ./clusters/prod-l3-azure/infra/ory/oathkeeper
  postBuild:
    substituteFrom:
      - kind: Secret
        name: oathkeeper-client-creds
  dependsOn:
    - name: ory-sync
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
