---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: ory
spec:
  install:
    remediation:
      retries: -1
  releaseName: pg-hydra
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: ory
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: ory-values
      valuesKey: values-postgresql.yaml
    - kind: Secret
      name: hydra-postgresql
      valuesKey: postgresqlPassword
      targetPath: auth.postgresPassword
    - kind: Secret
      name: hydra-postgresql
      valuesKey: hydraUsername
      targetPath: auth.username
    - kind: Secret
      name: hydra-postgresql
      valuesKey: hydraPassword
      targetPath: auth.password
