---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: matchmaker-service-optimiser
  namespace: optimiser
spec:
  install:
    remediation:
      retries: -1
  dependsOn:
    - name: node-optimiser
    - name: ipfs-optimiser
    - name: identity-service-optimiser
  chart:
    spec:
      chart: dscp-matchmaker-api
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
  - kind: ConfigMap
    name: optimiser-values
    valuesKey: values-dscp-matchmaker-service.yaml
  - kind: Secret
    name: optimiser-matchmaker-postgres-creds
    valuesKey: password
    targetPath: postgresql.auth.password
  interval: 10m0s
