logLevel: debug
userUri: 5GuU4dtu3d9nox95eU9B7jErvGpHD9Bq16VBJnVN3KKBBXZg
externalDscpNode:
  host: node-optimiser-dscp-node-0
  port: 9944
externalDscpIpfs:
  host: ipfs-optimiser-dscp-ipfs-api
  port: 5001
externalDscpIdentity:
  host: identity-service-optimiser-dscp-identity-service
  port: 3000
authType: EXTERNAL
ingress:
  ingressClassName: nginx-optimiser
  hostname: optimiser.dsch-l3.com
node:
  enabled: false
postgresql:
  primary:
    persistence:
      storageClass: enc-managed-csi
      size: 60Gi
