configmap:
  hashSumEnabled: true
service:
  api:
    port: 80
oathkeeper:
  managedAccessRules: false
  config:
    log:
      level: debug
      format: json
    serve:
      api:
        port: 4456
      proxy:
        port: 4455
    errors:
      fallback:
        - json
      handlers:
        json:
          enabled: true
          config:
            verbose: true
    mutators:
      noop:
        enabled: true
    authorizers:
      allow:
        enabled: true
      deny:
        enabled: true
    authenticators:
      oauth2_client_credentials:
        enabled: true
        config:
          token_url: 'https://oauth2.dsch-l3.com/oauth2/token'
      oauth2_introspection:
        enabled: true
        config:
          introspection_url: 'https://oauth2.dsch-l3.com/admin/oauth2/introspect'
      noop:
        enabled: true
ingress:
  proxy:
    enabled: false
  api:
    enabled: false
maester:
  enabled: false
