apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alice
resources:
  - source.yaml
  - dscp-api
  - dscp-identity-service
  - dscp-node
  - ipfs-node
configMapGenerator:
  - name: alice-values
    files:
      - values-dscp-node.yaml=dscp-node/values.yaml
      - values-dscp-ipfs.yaml=ipfs-node/values.yaml
      - values-dscp-api.yaml=dscp-api/values.yaml
      - values-dscp-identity-service.yaml=dscp-identity-service/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
