apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: monitoring
data:
  values.yaml: |
    watchIngressWithoutClass: false
    scope:
      enabled: true
    ingressClassResource:
      name: nginx-monitoring
      default: false
    service:
      type: LoadBalancer
      annotations: 
        service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
        external-dns.alpha.kubernetes.io/hostname: monitoring.dsch-l3.com
        cert-manager.io/cluster-issuer: letsencrypt-prod
        cert-manager.io/common-name: monitoring.dsch-l3.com
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    extraArgs:
      default-ssl-certificate: "monitoring/monitoring-dsch-l3-com-prod-tls"
    nodeSelector:
      kubernetes.io/os: linux
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Equal
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Equal
    containerPorts:
      http: 80
      https: 443
      metrics: 10254
