---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oathkeeper-sync
  namespace: ory
spec:
  interval: 1m
  path: ./clusters/kind-cluster/ory/oathkeeper
  dependsOn:
    - name: ory-sync
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
