---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ipfs-optimiser
  namespace: optimiser
spec:
  install:
    remediation:
      retries: -1
  dependsOn:
    - name: node-optimiser
  chart:
    spec:
      chart: dscp-ipfs
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
  - kind: ConfigMap
    name: optimiser-values
    valuesKey: values-dscp-ipfs.yaml
  interval: 10m
