---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bob-ipfs
  namespace: bob
spec:
  install:
    remediation:
      retries: -1
  dependsOn:
    - name: bob-node
  chart:
    spec:
      chart: sqnc-ipfs
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
  - kind: ConfigMap
    name: bob-values
    valuesKey: values-sqnc-ipfs.yaml
  interval: 10m
