---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 1m0s
  path: ./clusters/prod-l3-azure/infra/prometheus/instance
  prune: true
  dependsOn:
    - name: monitoring-sync
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
