grafana:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      ingress.kubernetes.io/force-ssl-redirect: '"true"'
    enabled: true
    hosts:
    - monitoring.dsch-l3.com
    ingressClassName: nginx-monitoring
    tls:
    - hosts:
      - monitoring.dsch-l3.com
      secretName: aks-grafana
