---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openapi-3pl-a
  namespace: 3pl-a
spec:
  install:
    remediation:
      retries: -1
  dependsOn:
    - name: dscp-identity-service
  chart:
    spec:
      chart: wasp-open-api
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
  - kind: ConfigMap
    name: 3pl-a-values
    valuesKey: values-wasp-open-api.yaml
  interval: 10m0s
