apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: oathkeeper-authenticated-paths
  namespace: ory
spec:
  match:
    url: <.*>/<v1>/<(?!swagger|api-docs).*>
    methods:
      - GET
      - POST
      - PUT
  authenticators:
    - handler: oauth2_introspection
      config:
        introspection_url: 'http://hydra-admin:4445/oauth2/introspect'
        scope_strategy: wildcard
        cache:
          enabled: false
  authorizer:
    handler: allow
  mutators:
    - handler: noop
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: oathkeeper-unauthenticated-paths
  namespace: ory
spec:
  match:
    url: <.*>/<(swagger|api-docs).*>
    methods:
      - GET
      - POST
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: hydra-admin
  namespace: ory
spec:
  match: 
    url: https://oauth2.dsch-l3.com/version
    methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
  authenticators:
    - handler: oauth2_client_credentials
      config:
        token_url: 'https://oauth2.dsch-l3.com/oauth2/token'
        required_scope: admin
  authorizer:
    handler: allow
