apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: dscp-authenticated-paths
  namespace: ory
spec:
  match:
    url: <.*>/<v1>/<(?!swagger|api-docs).*>
    methods:
      - GET
      - POST
      - PUT
  authenticators:
    - handler: oauth2_introspection
      config:
        introspection_url: 'https://oauth2.dsch-l3.com/admin/oauth2/introspect'
        scope_strategy: wildcard
        introspection_request_headers:
          Authorization: Basic $(oathkeeper_client_token)
  authorizer:
    handler: allow
  mutators:
    - handler: noop
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: dscp-unauthenticated-paths
  namespace: ory
spec:
  match:
    url: <.*>/<(swagger|api-docs).*>
    methods:
      - GET
      - POST
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: hydra-admin-authenticated-paths
  namespace: ory
spec:
  match:
    url: <.*>/<admin(?!/oauth2/introspect)|clients|keys|health|metrics|version|oauth2/auth/requests|oauth2/flush><.*>
    methods:
      - GET
      - POST
      - PUT
      - UPDATE
      - DELETE
  authenticators:
    - handler: oauth2_introspection
      config:
        introspection_url: 'https://oauth2.dsch-l3.com/admin/oauth2/introspect'
        scope_strategy: wildcard
        target_audience: 'admin'
        introspection_request_headers:
          Authorization: Basic $(oathkeeper_client_token)
  authorizer:
    handler: allow
  mutators:
    - handler: noop
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: hydra-admin-introspection-path
  namespace: ory
spec:
  match:
    url: <.*>/<oauth2/introspect|admin/oauth2/introspect>
    methods:
      - GET
      - POST
      - PUT
      - UPDATE
      - DELETE
  authenticators:
    - handler: oauth2_client_credentials
      config:
        token_url: 'https://oauth2.dsch-l3.com/oauth2/token'
  authorizer:
    handler: allow
  mutators:
    - handler: noop
