---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: matchmaker-service-3pl-b
  namespace: 3pl-b
spec:
  install:
    remediation:
      retries: -1
  dependsOn:
    - name: node-3pl-b
    - name: ipfs-3pl-b
    - name: identity-service-3pl-b
  chart:
    spec:
      chart: sqnc-matchmaker-api
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
  - kind: ConfigMap
    name: 3pl-b-values
    valuesKey: values-sqnc-matchmaker-service.yaml
  - kind: Secret
    name: 3pl-b-matchmaker-postgres-creds
    valuesKey: password
    targetPath: postgresql.auth.password
  interval: 10m0s
