---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 3pl-b-sync
  namespace: 3pl-b
spec:
  interval: 1m0s
  path: ./clusters/prod-l3-azure/3pl-b
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: secrets
      namespace: flux-system
