apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  name: enc-managed-csi
parameters:
  skuname: StandardSSD_LRS
provisioner: disk.csi.azure.com
allowVolumeExpansion: true
reclaimPolicy: Delete
diskEncryptionType: EncryptionAtRestWithCustomerKey
diskEncryptionSetID: /subscriptions/a8b51d77-6ba7-4a44-8361-f4dbac41f6c3/resourceGroups/L3-K8S-Prod/providers/Microsoft.Compute/diskEncryptionSets/l3-encrypted
volumeBindingMode: WaitForFirstConsumer
