---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx-sync
  namespace: monitoring
spec:
  interval: 1m0s
  path: ./clusters/prod-l3-azure/infra/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-sync
  namespace: monitoring
spec:
  interval: 1m0s
  path: ./clusters/prod-l3-azure/infra/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ory-sync
  namespace: ory
spec:
  interval: 1m0s
  path: ./clusters/prod-l3-azure/infra/ory
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
