---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: optimiser-sync
  namespace: optimiser
spec:
  interval: 1m0s
  path: ./clusters/prod-l3-azure/optimiser
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: secrets
      namespace: flux-system
