apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-values
  namespace: ory
data:
  values.yaml: |
    configmap:
      hashSumEnabled: true
    service:
      proxy:
        enabled: false
      api:
        port: 80
    oathkeeper:
      managedAccessRules: false
      config:
        log:
          level: debug
          format: json
        serve:
          api:
            port: 4456
          prometheus:
            port: 9000
        errors:
          fallback:
            - json
          handlers:
            json:
              enabled: true
              config:
                verbose: true
        mutators:
          noop:
            enabled: true
        authorizers:
          allow:
            enabled: true
          deny:
            enabled: true
        authenticators:
          oauth2_introspection:
            enabled: true
            config:
              introspection_url: http://hydra-admin:4445/oauth2/introspect
              scope_strategy: wildcard
          noop:
            enabled: true

    ingress:
      proxy:
        enabled: false
      api:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$1
          nginx.ingress.kubernetes.io/use-regex: "true"
          nginx.ingress.kubernetes.io/enable-global-auth: "false"
        hosts:
        - host: localhost
          paths:
          - path: /oathkeeper/(.*)
            pathType: ImplementationSpecific
    maester:
      enabled: false
