apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 3pl-b
resources:
  - source.yaml
  - dscp-node
  - dscp-ipfs
configMapGenerator:
  - name: 3pl-b-values
    files:
      - values-dscp-node.yaml=dscp-node/values.yaml
      - values-dscp-ipfs.yaml=dscp-ipfs/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
