---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-3pl-b
  namespace: 3pl-b
spec:
  install:
    remediation:
      retries: -1
  chart:
    spec:
      chart: sqnc-node
      version: '5.0.0'
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
  - kind: ConfigMap
    name: 3pl-b-values
    valuesKey: values-sqnc-node.yaml
  - kind: Secret
    name: blue-keys
    valuesKey: node_id
    targetPath: node.customNodeKey
  - kind: Secret
    name: blue-keys
    valuesKey: aura_seed
    targetPath: node.keys[0].seed
  - kind: Secret
    name: blue-keys
    valuesKey: grandpa_seed
    targetPath: node.keys[1].seed
  interval: 10m
