node:
  chain: l3-prod
  role: validator
  dataVolumeSize: 40Gi
  perNodeServices:
    setPublicAddressToExternal:
      enabled: false
  keys:
    - type: aura
      scheme: sr25519
    - type: gran
      scheme: ed25519
  flags:
    - "--rpc-external"
    - "--ws-external"
    - "--rpc-methods=Unsafe"
    - "--rpc-cors=all"
    - "--unsafe-ws-external"
    - "--unsafe-rpc-external"
    - "--prometheus-external"
    - "--bootnodes '/dns4/node-3pl-a-dscp-node-0-rc-p2p.3pl-a.svc.cluster.local/tcp/30333/p2p/12D3KooWNFPAiW78EeheYVVYuNXHFBNGZLVGFuf5BHCGBUmp28KU'"
  serviceMonitor:
    enabled: true
  enableStartupProbe: true
  enableReadinessProbe: true
storageClass: enc-managed-csi
image:
  tag: v8.0.0
