config:
  logLevel: info
  externalNodeHost: alice-node-dscp-node-0
  externalIpfsHost: alice-ipfs-dscp-ipfs-api
  externalIpfsPort: 5001
  accountKey: //Alice
  externalOrigin: "http://localhost:3080"
  externalPathPrefix: "alice/dscp-api"
ingress:
  paths:
    - "/alice/dscp-api/(.*)"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
#   className: nginx-alice
dscpIpfs:
  enabled: false
dscpNode:
  enabled: false
