config:
  logLevel: info
  externalNodeHost: alice-node-dscp-node-0
  externalIpfsHost: alice-ipfs-dscp-ipfs-api
  externalIpfsPort: 5001
  accountKey: //Alice
  externalOrigin: "http://localhost:3080"
  externalPathPrefix: "alice/dscp-api"
  authType: EXTERNAL
ingress:
  host: localhost
  paths:
    - "/alice/dscp-api/(.*)"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
ipfs:
  enabled: false
node:
  enabled: false
