---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-optimiser
  namespace: optimiser
spec:
  install:
    remediation:
      retries: -1
  chart:
    spec:
      chart: dscp-node
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
  - kind: ConfigMap
    name: optimiser-values
    valuesKey: values-dscp-node.yaml
  - kind: Secret
    name: green-keys
    valuesKey: node_id
    targetPath: node.customNodeKey
  - kind: Secret
    name: green-keys
    valuesKey: aura_seed
    targetPath: node.keys[0].seed
  - kind: Secret
    name: green-keys
    valuesKey: grandpa_seed
    targetPath: node.keys[1].seed
  interval: 10m
