apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: charlie
resources:
  - source.yaml
  - sqnc-node
  - sqnc-identity-service
  - ipfs-node
  - sqnc-api
configMapGenerator:
  - name: charlie-values
    files:
      - values-sqnc-node.yaml=sqnc-node/values.yaml
      - values-sqnc-ipfs.yaml=ipfs-node/values.yaml
      - values-sqnc-api.yaml=sqnc-api/values.yaml
      - values-sqnc-identity-service.yaml=sqnc-identity-service/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
