apiVersion: v1
data:
    account_seed: ENC[AES256_GCM,data:8xjtpYlxeRy/etKzjmP7AdSiykrUlgQf6xwqyox9IIBKGrSmCmYakyiOG7HPFgA/4sD8upqNGxNDDgnh1NTOK6qjqF6LryJx1F83DNWOjfrQFoICqiZlgKHWDsZfZp0IlFBqRF77Tl337xBkHFZGQA==,iv:DqUd/0hIl5JYjRZR5juAlXNtCJ9bFCjdRsAbnWPdwRY=,tag:C3DFnGvbaDogO0NmWaNkjg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: 3pl-a-keys
    namespace: 3pl-a
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-05T09:39:06Z"
    mac: ENC[AES256_GCM,data:rK37IEcUO+zshrWPPmi+csyFz647CwXoDmEL8HtUr1m+3nXCbXa+MDDbKIzaOZYagg1jj7CQGebqXIfAHK14tfdme749HU0LuGJjbngi+W5myeMaTOpLPWJayik5QSEC60mdapE07E3NzjlAtzcSUWUC5x4T2VhKfBLcA1Z5cU0=,iv:Jw5WGh3s/Sfi5HFnenxwyv2OAZp06yzYBq0gqd3I2Ag=,tag:Tmt4tX5K02NDjuLZbiBxig==,type:str]
    pgp:
        - created_at: "2023-04-05T09:39:05Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4D2akIMIvn7NISAQdAdFU3poYu+xxjx/B/xMqPX+ZiulhYINaE8lIiHJh4zRgw
            jDdayuUSSdy78Na0M17WcdN4Fww5z/NhktxodOd9ZG+oH4gu+SEEXtJG+VQZ8w8R
            1GgBCQIQ5FmsvePfLM7mfixBbyioUHKLpUojcwrfrzo6QDq7zZ9s/GOOv8OtMtUS
            rRiX1M5epBluc3DI0qj/RCaf3cPTtej0IkamfgMh7Stbz7WhVFRQsxbOrspwjyY0
            C0llBPNCufMOJg==
            =RSUS
            -----END PGP MESSAGE-----
          fp: 7FC689D6E47F98771C08D263A41D906A9C10B034
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
