apiVersion: v1
data:
    account_seed: ENC[AES256_GCM,data:8cdBk+n5b2wMlvsJaojZNUHqMKB8bC3FGyVK8hCGLbHKB/7XHtln8lCCHS8Hh2Tg1fWtqwh4QJKwKlwPZXt2KhgoZz59mWiYjD395NpIYb/flvIVbm7UvPts2addv1ie,iv:E8NyUSvLL5Rifz8Yd0UiFoTUYblPeOeln749Kc4i1sA=,tag:4LvOvVUfQr8EcGSmw/5tdQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: 3pl-a-keys
    namespace: 3pl-a
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-25T10:25:11Z"
    mac: ENC[AES256_GCM,data:g7md8aQDXa+1HG4C6Fvt18nVXZHKEVdjETkneq6TtYlcHxxgFtLWwWqNamiN/5/IKZiYVspOlMy0yXiz2EqEZdtCUGlLFmG+JPElj2RgsqtuvZ//6TC08jdJMwRz7AGP5TCzkUNBo1csuIa4W3eY3jDTr855ParMCZ3UOMa2lAM=,iv:7ucqUkjHOsfxEkgAQir7UqkuGs5grybfSNhW5nVQnnE=,tag:3lwTJ7WKVDlwwz/NDal1lA==,type:str]
    pgp:
        - created_at: "2023-04-25T10:25:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4D2akIMIvn7NISAQdA2238TfYGvmhMlUVYLf9nVwsKYDYXxuMRCJGdzo5VwR8w
            OxsdbEem8ixAp20RwHVsNeyEv+ncj3PUPvLS5/oen/b5RxjuNDlONRGYWZiCWw/w
            1GYBCQIQ2DUL6HUIqeOnSyDRViniozc7rFdKbHczl9ft5fNbCm6802ZpfDvYsUal
            M00BJ2gXIlHEiMQmroMzhzYJC+T+fbvz7RQtU1IHZzhNXPumXfTeuDlcQa0rnDZO
            MoCw6GPSpZs=
            =5BDI
            -----END PGP MESSAGE-----
          fp: 7FC689D6E47F98771C08D263A41D906A9C10B034
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
