apiVersion: v1
data:
    password: ENC[AES256_GCM,data:RkK28PIIAqzlpQuEFS75BcrVslNs1U10JcSU8GH+kXE=,iv:eWcqbd/XJRiqO7hOX14KaLDpS40Ujii0jHzax6JAbc4=,tag:eXWL1r6MAmvV3geLb9srBA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: 3pl-b-matchmaker-postgres-creds
    namespace: 3pl-b
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-11T11:56:22Z"
    mac: ENC[AES256_GCM,data:0/haT0D4C3n82zE6HMylbrK7o/+nB7qMo+48oeHdmjAHAoaUqfBbglswGfEaO/y6ilnNopgBqqgnl1NVIPyh6SulMUUVvhfnrAZLEJ503bDoMzmhghKovd1Rx1okgLMF/BLx/GKsTahhLzPAYkye9jUsTbGKyLBJx2b//8uJFY0=,iv:oRJKWgTQLqBTVwlR2+Z4FmN5cDREiejrVFcpS1SopTI=,tag:9J1+auKkN1E4oM4RRVTYcg==,type:str]
    pgp:
        - created_at: "2023-05-11T11:56:22Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4D2akIMIvn7NISAQdAFGSD2K1ToYv0JN5iJJcG/QMtRbwdJRzfDn/60LdlGUgw
            d0b314JjxFpc2mVD8V/hSg3/CirI/ZIGsHbuF3fkYl7gwfeVrgj5TQjiNdPib/NB
            1GgBCQIQk1G0UXleEpS9HkChNc1Z07TfT1/+lm4xfNazMpX1aLSv0DwxP35/8VzI
            jPszwL0lZOseDpHn6ggibWbKUPlvKXI38oz/mC/xkaVhEgh4V9pfpsMexqkxovuT
            71TCBF6GS4VqXw==
            =tBts
            -----END PGP MESSAGE-----
          fp: 7FC689D6E47F98771C08D263A41D906A9C10B034
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
