apiVersion: v1
data:
    babe_seed: ENC[AES256_GCM,data:gYuWbEe40+SXMx0mI7/FFNn1+y0ptIYUr16PR3FpxwH1+oiLjwrXOH5dF2fpEEyX9Zbus/pjjC9LCoHN+zKZZtwfdrJ3ZjWXg9mOKfOBdXS11Xf8lfh4LQ==,iv:jgSKzZ+AjAd+/6YWw+0IpR5fjAmDdPkahI+boDHSPBI=,tag:lDMfQVdlXZSYIra62W4FBA==,type:str]
    grandpa_seed: ENC[AES256_GCM,data:OmqKdXP82zujvMWxxV9KC+sUzFyeuvc+CWED+fBRVBf036P77vUp3klJIaxLvwJmeMTyaz1c0GbLa77eoIlfNPXXW/DRNrHIXiL8bKeqS6bIqZ7mGajtBmuHFr4Gn0jMRvtN9bYnSbY=,iv:GHan0dWQ/O0/ZJeTpmPjlxWIE876EdoM5UAYM/NGiC8=,tag:B4tbJykxfRupbTsPVzz+1Q==,type:str]
    node_id: ENC[AES256_GCM,data:2i8RuDdkbN7LbGAaRWncsRaOHAG0EF6Ep2YgvkUirodp0V24XA0Tkn3fYMpcBrkkNAozOR6Dxb8ReKzSVCyN4NbSX31qQYmS7BNtdRtlruYacZjZ4SsbyQ==,iv:cxccskRbrrqr9Nz9Yxe8vYFgpZjMSmygApnJNMQdGI8=,tag:2UJ9IWnxZON9tV+dxg2dNQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: blue-keys
    namespace: 3pl-b
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-25T10:25:12Z"
    mac: ENC[AES256_GCM,data:llUkrbBvSpn8ubMGqeOFvyrzVPhEDjftDYJG2JtCMWaPnrYmq3PZ59dVicPhvINR1z2Mnf6RPZA3gFjLiXOOPzYUebhuQaZ2zez9NPbd1Wr/B7EN7yoond54yP3YzGYA/Qh9kySz5Vvr5pN8ZoSl5bC+u8e7oVr/oTB2Zu7j1NI=,iv:FVn560pMX6lnX4+CGKhip5iT+bCLTVRHD0INzLXZT90=,tag:9Zc8UoVonci6rMYaP8Wwvg==,type:str]
    pgp:
        - created_at: "2023-04-25T10:25:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4D2akIMIvn7NISAQdAfq4PGtzQx/qLPp6yaWaDL8SMM1/kibVQtXgMNrGNW3ow
            UKCE7eFtd4dflV2woaOa3c+K9ZZxW9thgtnPmZzwLubKyDoQRnKZhBUOu1i1eqhE
            1GgBCQIQgQZoN9F4qE3+NbYt28UK45sV4U3cK7E4a3ucIoBuTxvrBmSpxiS0cXIm
            crW6t0UErqvJU6nSruQ8mN5bGm5RZQA4THSF+StM4PonUAgVs8B3IPnQrjSSePaO
            8ri0mLLg8z4Vsg==
            =TDiX
            -----END PGP MESSAGE-----
          fp: 7FC689D6E47F98771C08D263A41D906A9C10B034
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
