apiVersion: v1
data:
    aura_seed: ENC[AES256_GCM,data:xcFyxrNgTD/gTYwJgy6PlLvcVEQUodIcNcjPS9js8aHEKarNccUa7dL0tz1SubP+pkwse0I0mqd/QvVO4bm4mkoexhk7SpbKQgSSfZzMks/vtk58eM9Iuex+oYMIEoU2p/xTgw==,iv:1vBb8FN7N6R8DunYd9+jzgrM5Y2cOFDY8roIq5ROGmk=,tag:tx3FSSsyklsnkhAWMbI7Vw==,type:str]
    grandpa_seed: ENC[AES256_GCM,data:eTYVdWYRnt6KfGIyZhuT+sxutUc00H9OPunZFzbG3ex3q7KbPzZa3B9mwrMuCf9ftgyEKaxlvJU6oR4Y1GTcho+Tr2l7GLiPy/ejtxmX8azt4o//tx2OaNDR4BBM0JheWw/ndNNaif5NcZsN,iv:aMlTe2JYQX67woGOLEZ74w19WZT8L3Ly4o9EWLvKZQw=,tag:hICFvO5jIDTl4ejE+TPQGw==,type:str]
    node_id: ENC[AES256_GCM,data:7j3gnzxpTECllp9VqAScQ8EuGkQdxiUM0iucCMzZMwlciVsdoKX2htOrLbvlv42bJxgFmBucVZ+y+kNj531wxKKIkLQg+FKmSHea006bsW9V90sPAeu1MQ==,iv:dAVDZMpWakovC6auXkJGyMc82NxrK6/E6NXRwf7m0xw=,tag:H25NI3rr6Ve4U1wKHzYXcw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: blue-keys
    namespace: 3pl-b
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-05T09:39:06Z"
    mac: ENC[AES256_GCM,data:3CyDC2zv+wgKsyUx5puvuGc1gUWz3X7LuSGJ512gGIjYzYty6Dx0QVvQVxu+9tmq/t9f3nZS3LE5ZJq+rnVc7Ea+wpkOQZGsA6JM28G/wCaoALOx7ho1ayNL+czPcKvKYhlshgRQki6AYdn8O21UwJZfqzt+cmF1HUD6WyTTYBA=,iv:bqBItuR8MDVrgvfqpmR3k1kYUdL5F5vfAChdqPFDick=,tag:fjWp9dLmyKnvUltMYVor8w==,type:str]
    pgp:
        - created_at: "2023-04-05T09:39:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4D2akIMIvn7NISAQdAWk6bxKFTwsUugGCI9gQf3gF2skOC7hI5+Wvl0cMzRRAw
            PklMrzLvfow7lRyzSACeE2emSQnxK4NKJZsXFeQMSEy9N/cu4qk0Tkko2JzbaZ9S
            1GgBCQIQtpbAGSGvOwQTttGuCES/5A91UtI9qRzIHtZn/vUkv5nW1cyRKipMNOEg
            UdJz0oaNKRKYnsOfPwVqq4OpuQDj4dw0dpto+Qv9XC+gBb3SVEhKgTxisUt5t0Gy
            yKHciiPm5Kvt+A==
            =mKxe
            -----END PGP MESSAGE-----
          fp: 7FC689D6E47F98771C08D263A41D906A9C10B034
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
