apiVersion: v1
data:
  aura_seed: ZXJhc2Ugc2tpbiBwcml6ZSBlZ2cgZG9ua2V5IHBlYWNlIHN1cGVyIHN0b3J5IHZlcmIgZHJhbWEgZGljZSBlaWdodA==
  grandpa_seed: Z2FsYXh5IGlsbCBkaXZpZGUgZHVyaW5nIGJhciBzd2lmdCBqdW5nbGUgaG92ZXIgdmFsdmUgYmV0dGVyIGVsZXBoYW50IGZvbGxvdw==
  node_id: NTAzZmM2ZTU1MTc1Y2I3MjViZjEyODQ2M2Y5ZjFlYWE5NjAwYmY3ZTgzZTk3YzA3N2YzNWFjZTI2Yjk3ZTcxZQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: blue-keys
  namespace: 3pl-b
type: Opaque
