apiVersion: v1
data:
    hydraPassword: ENC[AES256_GCM,data:WWE4EtIQ7SqHYlMtd9HTEiXeRFlUa9+P,iv:UN3JZNTIvJm8WXrG6Rd92mewsQPWdx4J4ZeELeFc+kQ=,tag:iP3Gh11Hhiq1JChUyp4p7g==,type:str]
    hydraUsername: ENC[AES256_GCM,data:297LanNOjnQ=,iv:r8EVOR4c10lXUm0PX+DnFNXkjsdI2GADd5bcjJhuiAE=,tag:CJ1tuxJRL5nrq6vyqt0AyQ==,type:str]
    postgresqlPassword: ENC[AES256_GCM,data:kWjmsAOYgbA+fWg8ulZ3RVOooJ3OAYU8,iv:haFxoyaoqDH6wlgRUBpLRuYGPgNyIxZQmYPjw9Mfiyg=,tag:Gm8XMx8u3fStkzTTkk7csA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: hydra-postgresql
    namespace: ory
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-12T13:01:12Z"
    mac: ENC[AES256_GCM,data:IMXiagfhN5TCp+Kbj2EpOSSqrP05pDNlAOSLrODOTmmnWz+5gofG/Kl8P0zBma89+2QaOXQFS9PT5BRVHm+o01v5+c1hFFmi+nVJq0rR9heC47go5f4pZ6yKLUZGMv9Tfy3zrbtWMYun6UuUaS09QxCw5N0hRQ5cyUDaxRbooeQ=,iv:+/LCK+667YeJhcU4W2AbddC/N9Z0WwfY5Vy5XJyfbQI=,tag:Q6LZNZfBXzF4aJaOZyhG6Q==,type:str]
    pgp:
        - created_at: "2023-04-12T13:01:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4D2akIMIvn7NISAQdANNd9AoT4ipSl/Qlnai9gSogPlJ4enIQRL6we+jusVB0w
            6OXws9NfWoobxA6YwYW+jO0EwysvVjyc5APC+lCuey7HsO0MQiCqVRyAS8L43h24
            1GgBCQIQDQ2yDsXuVPrYe/xEdH0+ePEsDJo5fZ4SvpyvLZuSgzW+JF3lpFyg7y6c
            NGzP8zI4wum3f85iDz92KIAqnXv5Ty2z5Nv9Bh1XZ2lyq0mAV+M+mGJ4v8gJ9jlr
            u3HjHtl0Z67SHQ==
            =4ClF
            -----END PGP MESSAGE-----
          fp: 7FC689D6E47F98771C08D263A41D906A9C10B034
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
