apiVersion: v1
data:
    password: ENC[AES256_GCM,data:XKnAYaSt8ho3ymMEYQyR4jF3RwV0kTKuAOi+jDzLugs=,iv:BK/jyxa7O6HtzkeZAnXjjOMm/WryHShgEvQh1GtcIGc=,tag:9Cb7mkySC75+BwhP/+F31A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: optimiser-matchmaker-postgres-creds
    namespace: optimiser
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-11T11:56:23Z"
    mac: ENC[AES256_GCM,data:azVCBpPM6AlxZKnUfGUx7trFhrCi2jL9B2oOCNMNytwmjmIyAnnbhUFGDmD64UIKXJw6yQ4yP31T6MNwPk16STiJPEX3exwg7meu+W3f9Xfe18juhVpTyFgiWuazs8vIfNcu6MeEhBRydZ6yqWR25EPe6Xr/wo9NDWNFF/QMEa0=,iv:RTVZkpEuNTzAnL2cjNJ2l3JSBpFBMXwWZ/dqFKGS+xg=,tag:A5LBe7vT/0wylP4BDDv57A==,type:str]
    pgp:
        - created_at: "2023-05-11T11:56:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4D2akIMIvn7NISAQdAb5gLnlqGR7ChydqJQUf03LjrXgwl/SeJU1XeYnQFKn4w
            IUOpeMBA6fmBNkpZ8N9638LciLIzt4nEdR25PbonQBqPtXEum2SdCOBx5sQlaO+2
            1GgBCQIQJdbUsKxl/WyNvB7m7dQT0x9mo/bjsrtxe00ell2kDaLlq0PPLx9AnuhI
            BTCDTHrAHk3u7TMC9Te315ngD5kBPgPi4BacCVQ16Sfz3CBVQvYjSzYiqTHFrDFy
            URDxTYG3PUB8Ig==
            =aN5Q
            -----END PGP MESSAGE-----
          fp: 7FC689D6E47F98771C08D263A41D906A9C10B034
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
