apiVersion: v1
data:
    babe_seed: ENC[AES256_GCM,data:zHS9tztVwP47ndNj7IoepY147zh3VEDbaTYp0Wy/vKoHdzPEuB18YrdiGdURV8PKLnyxFiHwfL8BGvBfkxzsbBlelQdhCsVTHZJksjZ9dFzabcACNOFKc6cYb39Axmonp3+5ewlLFgg=,iv:MXwHbVwT+TMNKagi3ISuHSdZCD376p8Vke7PwEoRVuI=,tag:+NGdcxxH2No8vUgYWstGMw==,type:str]
    grandpa_seed: ENC[AES256_GCM,data:LmGJWhTZ3f0ghbV8n+bSQnOKB3sXSGwPlaDtsi8O0BH/jO64rvrNBrqYyTGw4aNY6/+DrOBeyoUJgrCOJixWzuksQrN0Q8FGnT3n4kubD1Zmsy7RDaNe4LkBBeT7gPXKa+DaTuMwRA8KXj48,iv:fqTNfzeIxAvse4W4qv198A3zHEKfjNrz4UXjOH69Gmk=,tag:dRAeb4zzXfqLqhVf1s5SPA==,type:str]
    node_id: ENC[AES256_GCM,data:5BKIziiokIv4XgWSwsPHHSm6X86xiUxdPFivOlCBsbdG2NEa/TTuMbUnb7/J6PZLkQKDcNojKT0qNKlhWNmx8qodTyhGKAibhuuRPjI5dayO0/Wwk2jY+Q==,iv:cAgPJ1GQzNy3sWO1QDH1t0gw68TO5OGAKcLe+ikdH9U=,tag:B+gj09X+/nSPA9DrHB26mQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: red-keys
    namespace: 3pl-a
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-25T10:25:13Z"
    mac: ENC[AES256_GCM,data:XNuA+kFVtt4xTeiGImewg/CuRmpvHp+ILy0Jo+T/lucUkbO1Mkq9ur9vBnIRLst1Lme0VreS8qcycbmHP5IfTysd6MqjXBsUx7i7XpF8xatd/ExpRWwdsObmvrQ1wZAZkWiQyyIryOnSzbRNIDmn7w9nLbXiofg8pG4uSk2pgaw=,iv:e8Lmw+SY6ThVfNo4409jiNlmFKzDwekz5MfuWwwwSG0=,tag:cMLDzjsnofDbGgndsQaV3A==,type:str]
    pgp:
        - created_at: "2023-04-25T10:25:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4D2akIMIvn7NISAQdAobdN8TjLiyqnS84wS/1+gN0YX62y+WIprkpCg09Lh3kw
            3ngaQCP7qv3F9eDS+NxA7PJ454rpT7Kkdz3TvD1kGa7lFfLK+MVsZoT5yW3sG5zq
            1GgBCQIQ3yQLcQh/WdIP4pyzHL0mhbJXNc3tjMfwPGf/kcwEgnzfVhRYSTh61z24
            cAeyNtq7WNtMzi6Lxx15xDAQyst2SUnksDPwoACbyavsObVJffuUs+RHdLaN+3Dg
            8mA1Ria2n5K2Pw==
            =/ujx
            -----END PGP MESSAGE-----
          fp: 7FC689D6E47F98771C08D263A41D906A9C10B034
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
