---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: identity-service-3pl-b
  namespace: 3pl-b
spec:
  install:
    remediation:
      retries: -1
  dependsOn:
    - name: node-3pl-b
  chart:
    spec:
      chart: dscp-identity-service
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
  - kind: ConfigMap
    name: 3pl-b-values
    valuesKey: values-dscp-identity-service.yaml
  interval: 10m0s
