logLevel: info
selfAddress: 5H9KATdvPSzdw5oCkXD2HoJ3Qx9voD5eRsmME33HMmeWPsVa
externalDscpNode:
  host: node-3pl-b-dscp-node-0
  port: 9944
externalOrigin: "https://3pl-b.dsch-l3.com"
externalPathPrefix: "/identity"
authType: EXTERNAL
ingress:
  className: nginx-3pl-b
  hostname: 3pl-b.dsch-l3.com
  paths:
    - path: "/identity/(.*)"
      pathType: Prefix
node:
  enabled: false
postgresql:
  persistence:
    storageClass: enc-managed-csi
    size: 1Gi
