logLevel: info
selfAddress: 5H9KATdvPSzdw5oCkXD2HoJ3Qx9voD5eRsmME33HMmeWPsVa
externalDscpNode:
  host: node-3pl-b-dscp-node-0
  port: 9944
externalOrigin: "https://3pl-b.dsch-l3.com"
externalPathPrefix: "identity"
authType: EXTERNAL
apiVersion: v1
ingress:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  ingressClassName: nginx-3pl-b
  hostname: 3pl-b.dsch-l3.com
  paths:
    - path: "/identity/(.*)"
      pathType: Prefix
node:
  enabled: false
postgresql:
  primary:
    persistence:
      storageClass: enc-managed-csi
      size: 1Gi
image:
  tag: v1.8.27
