apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: optimiser
resources:
  - source.yaml
  - sqnc-node
  - sqnc-ipfs
  - sqnc-identity-service
  - sqnc-matchmaker-service
  - nginx
  - wasp-open-api
configMapGenerator:
  - name: optimiser-values
    files:
      - values-sqnc-node.yaml=sqnc-node/values.yaml
      - values-sqnc-ipfs.yaml=sqnc-ipfs/values.yaml
      - values-sqnc-identity-service.yaml=sqnc-identity-service/values.yaml
      - values-sqnc-matchmaker-service.yaml=sqnc-matchmaker-service/values.yaml
      - values-nginx.yaml=nginx/values.yaml
      - values-wasp-open-api.yaml=wasp-open-api/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
