apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: optimiser
resources:
  - source.yaml
  - dscp-node
  - dscp-ipfs
  - dscp-identity-service
  - nginx
  - wasp-open-api
configMapGenerator:
  - name: optimiser-values
    files:
      - values-dscp-node.yaml=dscp-node/values.yaml
      - values-dscp-ipfs.yaml=dscp-ipfs/values.yaml
      - values-dscp-identity-service.yaml=dscp-identity-service/values.yaml
      - values-nginx.yaml=nginx/values.yaml
      - values-wasp-open-api.yaml=wasp-open-api/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
