---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: identity-service-optimiser
  namespace: optimiser
spec:
  install:
    remediation:
      retries: -1
  dependsOn:
    - name: node-optimiser
  chart:
    spec:
      chart: sqnc-identity-service
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
  - kind: ConfigMap
    name: optimiser-values
    valuesKey: values-sqnc-identity-service.yaml
  interval: 10m0s
