logLevel: info
selfAddress: 5E1VuxBbFbfVsQo3Z27MZkzAH18gzdAHbDNTog7tsEstcpnT
externalDscpNode:
  host: node-optimiser-dscp-node-0
  port: 9944
externalOrigin: "https://optimiser.dsch-l3.com"
externalPathPrefix: "identity"
authType: EXTERNAL
apiVersion: v1
ingress:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  ingressClassName: nginx-optimiser
  hostname: optimiser.dsch-l3.com
  paths:
    - path: "/identity/(.*)"
      pathType: Prefix
node:
  enabled: false
postgresql:
  persistence:
    storageClass: enc-managed-csi
    size: 1Gi
image:
  tag: v1.8.26
