---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ipfs-3pl-b
  namespace: 3pl-b
spec:
  install:
    remediation:
      retries: -1
  dependsOn:
    - name: node-3pl-b
  chart:
    spec:
      chart: sqnc-ipfs
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
  - kind: ConfigMap
    name: 3pl-b-values
    valuesKey: values-sqnc-ipfs.yaml
  interval: 10m
